"""Generate native tool contracts and copy the exact Android tool artwork. --check never writes."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
KOTLIN = ROOT / 'composeApp/src/commonMain/kotlin/org/walks/gamecopilot'

def generate(harmony):
    spec = json.loads((ROOT / 'cross-platform/random-tools.json').read_text(encoding='utf-8'))
    ets = harmony / 'entry/src/main/ets'
    kt = '// Generated by scripts/sync-random-tools.py. Edit cross-platform/random-tools.json.\npackage org.walks.gamecopilot.theme\n\nobject RandomToolDesign {\n'
    ark = '// Generated by Android scripts/sync-random-tools.py. Do not edit.\nexport class RandomToolDesign {\n'
    for group in ['dimensions', 'colors', 'timing']:
        for key, value in spec[group].items():
            is_color = group == 'colors'
            kvalue = '0xFF' + value[1:] if is_color else str(float(value))
            avalue = json.dumps(value)
            kt += f'    const val {key}: {"Long" if is_color else "Double"} = {kvalue}\n'
            ark += f'  static readonly {key}: {"string" if is_color else "number"} = {avalue};\n'
    kt += '}\n'; ark += '}\n'
    outputs = {KOTLIN / 'theme/RandomToolDesign.kt': kt.encode(), ets / 'theme/RandomToolDesign.ets': ark.encode()}

    # Keep asset selection in Android's existing enum; no second mapping to maintain.
    enum = (KOTLIN / 'ui/page/random/AddNewRandom.kt').read_text(encoding='utf-8')
    mappings = re.findall(r'(Finger|Card|Dice|Coin|Wheel|AnswerBook)\(RANDOM_PAGE_CONFIG_CATE_\w+, Res.drawable.(\w+)\)', enum)
    assert len(mappings) == 6, 'Android RandomCate structure changed; update exporter'
    names = {'Finger':'FINGER','Card':'CARD','Dice':'DICE','Coin':'COIN','Wheel':'WHEEL','AnswerBook':'ANSWER_BOOK'}
    visual = "// Generated from Android RandomCate and original artwork.\nimport { RandomCate } from '../model/enums/RandomCate';\nexport class RandomToolVisuals {\n  static getIcon(cate: RandomCate): Resource {\n    switch (cate) {\n"
    for cate, resource in mappings:
        src = ROOT / 'composeApp/src/commonMain/composeResources/drawable' / (resource + '.png')
        if src.exists():
            outputs[harmony / 'entry/src/main/resources/base/media' / ('shared_' + resource + '.png')] = src.read_bytes()
        else:
            import xml.etree.ElementTree as ET
            vector = ET.parse(src.with_suffix('.xml')).getroot()
            attr = '{http://schemas.android.com/apk/res/android}'
            svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">'
            for path in vector:
                fill = path.get(attr + 'fillColor', '#00000000')
                svg += '<path d="' + path.get(attr + 'pathData') + '" fill="' + ('none' if fill == '#00000000' else fill) + '" stroke="' + path.get(attr + 'strokeColor') + '" stroke-width="' + path.get(attr + 'strokeWidth') + '" stroke-linecap="round" stroke-linejoin="round"/>'
            outputs[harmony / 'entry/src/main/resources/base/media' / ('shared_' + resource + '.svg')] = (svg + '</svg>').encode()
        visual += f"      case RandomCate.{names[cate]}: return $r('app.media.shared_{resource}');\n"
    outputs[harmony / 'entry/src/main/resources/base/media/shared_icon_edit.png'] = (ROOT / 'composeApp/src/commonMain/composeResources/drawable/icon_edit.png').read_bytes()
    visual += "      default: return $r('app.media.shared_icon_card');\n    }\n  }\n}\n"
    outputs[ets / 'components/RandomToolVisuals.ets'] = visual.encode()

    rules = spec['rules']
    # The bounds / sample expressions below are emitted to both languages together.
    kr = 'package org.walks.gamecopilot.theme\n\n// Generated; rule values and vectors live in cross-platform/random-tools.json.\nobject RandomToolRules {\n'
    ar = '// Generated; rule values and vectors live in Android cross-platform/random-tools.json.\nexport class RandomToolRules {\n'
    kr += '    private fun integer(text: String, fallback: Int): Int = text.trim().toIntOrNull() ?: fallback\n'
    ar += '  private static integer(text: string, fallback: number): number {\n    const clean: string = text.trim();\n    const value: number = Number(clean);\n    return /^[+-]?\\d+$/.test(clean) && Number.isSafeInteger(value) && value >= -2147483648 && value <= 2147483647 ? value : fallback;\n  }\n'
    for name, func in [('low', 'min'), ('high', 'max')]:
        a = f'integer(first, {rules["firstFallback"]})'; b = f'integer(second, {rules["secondFallback"]})'
        kr += f'    fun {name}(first: String, second: String): Int = {func}Of({a}, {b}).coerceIn({rules["diceMin"]}, {rules["diceMax"]})\n'
        ar += f'  static {name}(first: string, second: string): number {{ return Math.max({rules["diceMin"]}, Math.min({rules["diceMax"]}, Math.{func}(this.{a}, this.{b}))); }}\n'
    kr += '    fun dice(first: String, second: String, sample: Double): Int {\n        require(sample.isFinite() && sample >= 0 && sample < 1)\n        val low = low(first, second)\n        return low + kotlin.math.floor(sample * (high(first, second) - low + 1)).toInt()\n    }\n'
    ar += '  static dice(first: string, second: string, sample: number): number {\n    if (!Number.isFinite(sample) || sample < 0 || sample >= 1) throw new Error("Sample must be in [0, 1)");\n    const low: number = this.low(first, second);\n    return low + Math.floor(sample * (this.high(first, second) - low + 1));\n  }\n'
    kr += f'    fun heads(sample: Double): Boolean {{\n        require(sample.isFinite() && sample >= 0 && sample < 1)\n        return sample < {rules["primaryProbability"]}\n    }}\n}}\n'
    ar += f'  static heads(sample: number): boolean {{\n    if (!Number.isFinite(sample) || sample < 0 || sample >= 1) throw new Error("Sample must be in [0, 1)");\n    return sample < {rules["primaryProbability"]};\n  }}\n}}\n'
    outputs[KOTLIN / 'theme/RandomToolRules.kt'] = kr.encode()
    outputs[ets / 'theme/RandomToolRules.ets'] = ar.replace('this.', 'RandomToolRules.').encode()
    return outputs

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--harmony', type=Path, default=ROOT.parent / 'YiGameCopilotX-Harmony')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changed = []
    for file, expected in generate(args.harmony).items():
        if not file.exists() or file.read_bytes() != expected:
            changed.append(str(file))
            if not args.check:
                file.parent.mkdir(parents=True, exist_ok=True)
                file.write_bytes(expected)
    if changed and args.check:
        raise SystemExit('Tool contract / artwork drift:\n' + '\n'.join(changed))
    print('Tool dimensions, colors, timings, rules and 6 icon mappings verified' if args.check else 'Generated both native tool contracts and copied Android artwork')

if __name__ == '__main__':
    main()
