"""Use Android's design system as the source of truth for native Harmony UI.

Run with --check in verification, or without it to regenerate the two ETS files.
"""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--harmony', type=Path, default=ROOT.parent / 'YiGameCopilotX-Harmony')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
android = ROOT / 'composeApp/src/commonMain/kotlin/org/walks/gamecopilot/theme'
harmony = args.harmony / 'entry/src/main/ets/theme'
source = (android / 'DesignSystem.kt').read_text(encoding='utf-8')
target = harmony / 'DesignSystem.ets'
output = target.read_text(encoding='utf-8')
count = 0
for name in ['AppColors', 'AppSpacing', 'AppCornerRadius', 'AppElevation', 'AppFontSize', 'AppIconSize']:
    body = re.search(r'data class ' + name + r'\((.*?)\n\)', source, re.S).group(1)
    values = re.findall(r'val (\w+): (Color|Dp) = (Color\(0x[0-9A-F]+\)|\d+\.dp)', body)
    assert values, name
    lines = []
    for key, kind, value in values:
        rendered = "'#" + value[10:-1] + "'" if kind == 'Color' else value[:-3]
        lines.append(f"  static readonly {key}: {'string' if kind == 'Color' else 'number'} = {rendered};")
    replacement = 'export class ' + name + ' {\n' + '\n'.join(lines) + '\n}'
    output, n = re.subn(r'export class ' + name + r' \{.*?\n\}', replacement, output, flags=re.S)
    assert n == 1, name
    count += len(values)

theme = (android / 'Theme.kt').read_text(encoding='utf-8')
schemes = {}
for mode in ['Light', 'Dark']:
    body = re.search(r'private val ' + mode + r'ColorScheme = \w+ColorScheme\((.*?)\n\)', theme, re.S).group(1)
    schemes[mode] = dict(re.findall(r'(\w+) = Color\(0xFF([0-9A-F]{6})\)', body))
    # ArkUI uses the same outline for the subtle secondary separator.
    schemes[mode]['outlineVariant'] = schemes[mode]['outline']
keys = list(schemes['Light'])
colors = '// Generated by scripts/sync-harmony-design.py in the Android project.\n'
colors += 'export interface ThemeColorScheme {\n' + ''.join(f'  {k}: string;\n' for k in keys) + '}\n\n'
for mode, values in schemes.items():
    colors += f'export const {mode}ColorScheme: ThemeColorScheme = {{\n'
    colors += ''.join(f"  {k}: '#{v}',\n" for k, v in values.items()) + '};\n\n'
colors += 'export function getColorScheme(isDark: boolean): ThemeColorScheme {\n  return isDark ? DarkColorScheme : LightColorScheme;\n}\n'
different = []
for path, contents in [(target, output), (harmony / 'ThemeColors.ets', colors)]:
    if path.read_text(encoding='utf-8') != contents:
        different.append(path.name)
        if not args.check:
            path.write_text(contents, encoding='utf-8', newline='\n')
if args.check and different:
    raise SystemExit('Design drift: ' + ', '.join(different))
print(f'{count} design tokens and {len(keys)} light/dark theme roles verified' if args.check else 'Synchronized Android design to Harmony')
