"""Keep the offline policy identical in Android, Harmony and the public HTML copy."""
import argparse
import html
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
parser.add_argument('--harmony', type=Path, default=root.parent / 'YiGameCopilotX-Harmony')
args = parser.parse_args()
body = (root / 'docs/store/vivo/privacy-domestic.txt').read_text(encoding='utf-8').strip()
literal = json.dumps(body, ensure_ascii=False)
outputs = {
    root / 'composeApp/src/commonMain/kotlin/org/walks/gamecopilot/privacy/DomesticPrivacyPolicy.kt':
        '// Generated by scripts/sync-domestic-privacy.py. Edit docs/store/vivo/privacy-domestic.txt.\n'
        'package org.walks.gamecopilot.privacy\n\n'
        'object DomesticPrivacyPolicy {\n    const val BODY = ' + literal.replace('$', r'\$') + '\n}\n',
    args.harmony / 'entry/src/main/ets/privacy/DomesticPrivacyPolicy.ets':
        '// Generated from the Android mainline by scripts/sync-domestic-privacy.py.\n'
        'export class DomesticPrivacyPolicy {\n  static readonly body: string = ' + literal + ';\n}\n',
    root / 'docs/store/vivo/privacy-domestic.html':
        '<!doctype html>\n<html lang="zh-CN"><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        '<title>桌游助手隐私政策（国内商店版）</title>'
        '<style>body{max-width:48rem;margin:3rem auto;padding:0 1.3rem;line-height:1.85;'
        'font:16px/1.85 system-ui,sans-serif;color:#242632;background:#fafaf8}'
        'article{white-space:pre-wrap;overflow-wrap:anywhere}</style>'
        '<article>' + html.escape(body) + '</article></html>\n',
}
for path, content in outputs.items():
    if args.check:
        if not path.exists() or path.read_text(encoding='utf-8') != content:
            raise SystemExit('Privacy text out of sync: ' + str(path))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8', newline='\n')
print('Domestic privacy copies match.' if args.check else 'Generated domestic privacy copies.')
