"""Generate the full-channel policy for public HTML, KMP and Harmony from one source."""
import argparse
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
parser.add_argument('--harmony', type=Path, default=ROOT.parent / 'YiGameCopilotX-Harmony')
args = parser.parse_args()
body = (ROOT / 'docs/store/privacy-full.txt').read_text(encoding='utf-8').strip()
literal = json.dumps(body, ensure_ascii=False)
url = 'https://wingsword.github.io/YiGameCopilotX/store/privacy-full.html'
deepseek = 'https://cdn.deepseek.com/policies/zh-CN/deepseek-privacy-policy.html'
escaped = html.escape(body)
linked = re.sub(r'https?://[^\s，。]+', lambda match: '<a href="' + match[0] + '">' + match[0] + '</a>', escaped)
outputs = {
    ROOT / 'composeApp/src/commonMain/kotlin/org/walks/gamecopilot/privacy/FullPrivacyPolicy.kt':
        '// Generated by scripts/sync-full-privacy.py. Edit docs/store/privacy-full.txt.\n'
        'package org.walks.gamecopilot.privacy\n\nobject FullPrivacyPolicy {\n'
        f'    const val URL = "{url}"\n    const val AI_POLICY_URL = "{deepseek}"\n'
        '    const val BODY = ' + literal.replace('$', r'\$') + '\n}\n',
    args.harmony / 'entry/src/main/ets/privacy/FullPrivacyPolicy.ets':
        '// Generated from the Android mainline by scripts/sync-full-privacy.py.\n'
        'export class FullPrivacyPolicy {\n'
        f'  static readonly url: string = "{url}";\n  static readonly aiPolicyUrl: string = "{deepseek}";\n'
        '  static readonly body: string = ' + literal + ';\n}\n',
    ROOT / 'docs/store/privacy-full.html':
        '<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        '<title>桌游助手隐私政策（完整版）</title>'
        '<style>body{max-width:48rem;margin:3rem auto;padding:0 1.3rem;'
        'font:16px/1.85 system-ui,sans-serif;color:#242632;background:#fafaf8}'
        'article{white-space:pre-wrap;overflow-wrap:anywhere}a{color:#475abe}</style></head>'
        '<body><main><article>' + linked + '</article></main></body></html>\n',
}
for path, content in outputs.items():
    if args.check:
        if not path.exists() or path.read_text(encoding='utf-8') != content:
            raise SystemExit('Full privacy text out of sync: ' + str(path))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8', newline='\n')
print('Full privacy copies match.' if args.check else 'Generated full privacy copies.')
