// Generated by scripts/sync-random-tools.py. Edit cross-platform/random-tools.json.
package org.walks.gamecopilot.theme

object RandomToolDesign {
    const val stageWidth: Double = 560.0
    const val stageHeight: Double = 286.0
    const val stageMinHeight: Double = 176.0
    const val stageRadius: Double = 26.0
    const val stagePaddingX: Double = 20.0
    const val stagePaddingY: Double = 18.0
    const val tileWidth: Double = 88.0
    const val tileHeight: Double = 60.0
    const val tileRadius: Double = 20.0
    const val tileIcon: Double = 24.0
    const val dockRadius: Double = 26.0
    const val headerIcon: Double = 26.0
    const val headerIconBox: Double = 44.0
    const val diceSize: Double = 112.0
    const val diceRadius: Double = 22.0
    const val diceDot: Double = 9.0
    const val diceDotOffset: Double = 13.5
    const val diceLift: Double = 26.0
    const val coinSize: Double = 116.0
    const val coinLift: Double = 34.0
    const val actionHeight: Double = 54.0
    const val iconDarkInset: Double = 2.0
    const val diceStart: Long = 0xFF13CE73
    const val diceEnd: Long = 0xFF8AF0B8
    const val diceInk: Long = 0xFF07130D
    const val diceFace: Long = 0xFFFFFFFF
    const val diceFaceMiddle: Long = 0xFFF4F4F4
    const val diceFaceEnd: Long = 0xFFEAEAEA
    const val coinStart: Long = 0xFFFFA51F
    const val coinEnd: Long = 0xFFFFD17A
    const val coinInk: Long = 0xFF1B1000
    const val coinFront: Long = 0xFFFFD26A
    const val coinFrontEdge: Long = 0xFFF1B938
    const val coinFrontInk: Long = 0xFF8B4513
    const val coinBack: Long = 0xFFD6DBE3
    const val coinBackEdge: Long = 0xFFAAB2BF
    const val coinBackInk: Long = 0xFF2F4F4F
    const val iconDarkSurface: Long = 0xFFE5E5EB
    const val diceDuration: Double = 1450.0
    const val coinDuration: Double = 1000.0
    const val diceSecondaryDuration: Double = 1120.0
}
